source: app 
destination: dist

assets:
  dirname: assets
  baseurl: /assets/
  sources:
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/components
    - _assets/images
  js_compressor: ~
  css_compressor: ~
  autosize: false
  cachebust: none
  cache: false
  gzip: []
  debug: false
  version: 1
  

# ftp_host: 'yourdomain.com'
# ftp_dir: '/web/site/root'
# ftp_passive: false

# optional
# ftp_port: 21                  # default 21
# ftp_username: 'your_user'     # default read from stdin
# ftp_password: 'your_ftp_pass' # default read from stdin
# ftp_secure: false              # default false
